const ActionTypes = {
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  SET_THEME: 'SET_THEME',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  SET_FAVORITES: 'SET_FAVORITES',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  ADD_TO_CART: 'ADD_TO_CART',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
};

export default ActionTypes;
