const ActionTypes = {
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  SET_THEME: 'SET_THEME',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
};

export default ActionTypes;
