const API_ENDPOINTS = {
  GET_SLIDERS: '/get_banner_sliders',
  GET_SHOES_SLIDER: '/get_shoes_sliders',
  GET_BRANDS: '/get_brands',
  GET_PRODUCTS: '/get_products',
  GET_PROMOTIONS: '/get_promotions',
  GET_PROMOTION_DETAIL: '/get_promotion_detail',
  GET_NEW_ARRIVAL_PRODUCTS: '/get_products_new_arrival',
  GET_RECOMMENDED_PRODUCTS: '/get_products_recommended',
  GET_POPULAR_PRODUCTS: '/get_products_popular',
  GET_PRODUCT_DETAIL: '/get_product_detail',
  SEARCH_PRODUCTS: '/products/search',
  GET_PRODUCTS_BY_BRAND: '/get_products_by_brand',
  SEND_OTP: '/register-with-phone',
  CREATE_ACCOUNT: '/verify-otp',
  SEND_OTP_FORGOT_PASSWORD: '/forget-password',
  CHANGE_PASSWORD: '/verify-otp-and-reset-password',
  LOGIN: '/login-with-phone',
  GET_USER_INFO: '/customer-profile',
  UPDATE_USER_INFO: '/update-profile',
  LOGIN_WITH_GMAIL: '/google-login',
  CHECKOUT: '/orders',
  GET_ORDER_HISTORY: '/order/history',
  GET_ORDER_HISTORY_DETAIL: '/order/detail',
  LOGOUT: '/logout',
  DELETE_ACCOUNT: '/delete-account',
};

export default API_ENDPOINTS;
